// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/27/2025, 11:06:54 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/muhammadhamza/Desktop/Brainity-Solutions/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/plugins/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/composables/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/utils/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;