// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/28/2025, 11:34:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/muhammadhamza/Desktop/Brainity-Solutions/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/plugins/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/composables/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/utils/**/*.{js,ts,mjs}","/Users/muhammadhamza/Desktop/Brainity-Solutions/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/muhammadhamza/Desktop/Brainity-Solutions/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;